const statuses = {
  SUCCESSFUL_STATUS: 200,
  SUCCESSFULLY_CREATED: 201,
  MISSING_FIELDS: 400,
  INVALID_FIELDS: 401,
  MISSING_REQUIREMENT: 422,
  INVALID_TOKEN: 401,
};

export default statuses;
